server:
  port: 8083

spring:
  profiles:
    # 使用 dev 环境
    active: dev
  application:
    name: rbac
  datasource:
    driver-class-name: ${rbac.datasource.driver-class-name}
    url: jdbc:mysql://${rbac.datasource.host}:${rbac.datasource.port}/${rbac.datasource.database}?useSSL=false&serverTimezone=Asia/Shanghai
    username: ${rbac.datasource.username}
    password: ${rbac.datasource.password}
  cache:
    type: redis
  data:
    redis:
      host: localhost
      port: 6379
      database: 2

mybatis:
  # mapper配置文件
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.ymjrhk.rbac.entity
  configuration:
    # 开启驼峰命名
    map-underscore-to-camel-case: true
    # 打开 MyBatis SQL 日志
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

logging:
  level:
    root: info # 全局默认：INFO
    com.ymjrhk.rbac: debug # 你自己的业务代码：DEBUG
    org.springframework.cache: debug # 打日志确认是否走缓存
#  pattern:
#    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} %-5level %X{pid} --- [%thread] %logger - %msg%n"

rbac:
  jwt:
    secret-key: ${rbac.jwt.secret-key}
    ttl: ${rbac.jwt.ttl}

# springdoc-openapi项目配置
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
# knife4j的增强配置，不需要增强可以不配
knife4j:
  enable: true
  setting:
    language: zh_cn

#mybatis 分页插件
pagehelper:
  helper-dialect: mysql
  reasonable: false # 对 pageNum / pageSize 做“合理化兜底”，pageNum ≤ 0 自动变成 1，pageNum > 总页数 自动变成最后一页，pageSize ≤ 0 自动变成默认值
#  support-methods-arguments: true # 允许从方法参数中自动获取分页参数 List<User> list = userMapper.list(pageNum, pageSize); 系统会自动识别且参数名必须是 pageNum / pageSize
#  params: count=countSql # reasonable: true （无用）